### ISSUE TITLE
GenOpt-EnergyPlus

### ISSUE THREAD

**Issue by Fan-Feng** [lbl-srg/GenOpt#10]
Hi,
I'm running GenOpt with EnergyPlus. But I found all Windows release of  EnergyPlus version 8.6 and prior release could not be downloaded anymore because they contained a vulnerability.  
And would you mind updating the examples for EnergyPlus to provide some examples for EnergyPlus version after 8.7? This will be greatly appreciated.

Best regards,
Fan

**Comment by mwetter** [comment]
@faithefeng : If you update the idf file, they should also work with more recent versions of EnergyPlus. Alternatively, I suggest you look into the other simpler examples in the `examples` directory and the user manual to see how to set up GenOpt.
