### ISSUE TITLE
GenOpt using Dymola or OpenModelica

### ISSUE THREAD

**Issue by AHaumer** [lbl-srg/GenOpt#13]
@mwetter I have a few questions, then I could correct my enclosed description and run optimizations with translated / executable model not only compiled with Dymola but also with OpenModelica. 
[GenOpt-DymolaOpenModelica.pdf](https://github.com/user-attachments/files/15752609/GenOpt-DymolaOpenModelica.pdf)
I created a setup where:
* GenOpt writes Param.txt using Param_Template.txt
* GenOpt calls the executable model
* The model writes the criterion to Result.txt
* GenOpt reads Result.txt and decides the next steps
The question is:
How should I have files copied to the temporary directory (created by GenOpt) of the simulation run?
As a first approach, I misused the Template and Input section in GenOpt.ini, but this failes for binaries or executables.
My executables require to be called in the same directory as the other files are located. 
There are some additional files necessary:
* init.xml           (the file read initially by the model from OpenModelica, except the parameters to be optimized)
* JacA.bin         (a file needed by the model from OpenModelica)
* Reference.txt  (measured trajectories)
* MyModel.exe (the executable itself)
In the end I could provide two simple examples that work both with Dymola and OpenModelica, 
using a small library to read parameters and calculate the criterion, writing its value to a file at the end of the simulation.
Thanks for help!
PS: If I would know how to access the subdirectory used for a single simulation run, 
I could manage copying the necessary files with a batch-file.

**Comment by mwetter** [comment]
@AHaumer : For text files, it is OK to "misuse" the `Template` and `Input` section, but as you wrote, I don't think that works for binary files.
For binary files, you could try a "trick" in writing a batch file that copies
```
copy \"%Simulation.Files.Template.Path1%\\JacA.bin\" .
copy \"%Simulation.Files.Template.Path1%\\MyModel.exe\" .
... // repeat for each binary file.
// And then call the executable
MyModel.exe
```
This batch file becomes an input template file for GenOpt. Then, GenOpt will replace ``%Simulation.Files.Template.Path1%``  with the corresponding location, copy the file to the temporary directory, change the current directory to the temporary directory and execute the batch file. Because the file is executed from the temporary directory, copying to `.` should work.

**Comment by AHaumer** [comment]
Thanks @mwetter sounds good - I'll try that and adjust my description.
Are you interested in getting my small "how-to" along with the examples?

**Comment by mwetter** [comment]
@AHaumer : Thanks for your offer. I think it would be nice to put your "how-to", or a link to it, at https://simulationresearch.lbl.gov/GO/download.html

**Comment by AHaumer** [comment]
I had to adjust your proposal a little bit but now it works!
We don't need the replacement done by GenOpt. 
The batch file `DoOM.bat` now is simply:
`@echo off
SET PATH=C:/OM/v1_22_3/bin/;%PATH%;
SET ERRORLEVEL=
copy ..\MyModel_JacA.bin .
copy ..\MyModel.exe .
CALL MyModel.exe
SET RESULT=%ERRORLEVEL%
EXIT /b %RESULT%`
and the command in SimulationStart in GenOpt's cfg is just:
`  Command = "DoOM.bat";`
I have to enhance my description, then I'll provide it along with an example.
@mwetter thanks a lot!
